version: "5.0.2"

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    restart: always
    ports:
      - "8080:80"
    volumes:
      - app-volume:/usr/share/nginx/html
    depends_on:
      - "frontend"
      - "backend"
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      target: server
    environment:
      - "APP_PORT=4000"
      - "LOG_LEVEL=debug"
    ports:
      - "4000:4000"
  frontend:
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
      target: client
    volumes:
      - app-volume:/prod/client/dist
    ports:
      - "3001:3001"
volumes:
  app-volume: